targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
          checked: true
          create_factory: true
          create_to_json: true
          field_rename: snake
          include_if_null: false
      riverpod_generator:
        options:
          provider_name_prefix: ""
          provider_family_name_prefix: ""
          provider_name_suffix: "Provider"
          provider_family_name_suffix: "Provider"
