name: dog_search
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.6.0

dependencies:
  auto_route: ^9.2.2
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_gen_runner: ^5.8.0
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.16
  fpdart: ^1.1.1
  freezed_annotation: ^2.4.4
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  hooks_riverpod: ^2.6.1
  json_annotation: ^4.9.0
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.4.2
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.3.5

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner:
  change_app_package_name: ^1.4.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  retrofit_generator: ^9.1.7
  riverpod_generator: ^2.6.3
  very_good_analysis: ^7.0.0

flutter_gen:
  output: lib/gen/
  assets:
    enabled: true
  fonts:
    enabled: true

flutter:
  uses-material-design: true
  assets:
    - assets/env/
    - assets/svg/
